#!/usr/bin/python
# coding: utf-8

# Copyright (c) 2014 Mountainstorm
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


import os
import sys
from grammar import GrammarStore
from ctags_formatter import CTagsFormatter


if __name__ == u'__main__':
    if len(sys.argv) != 2:
        print(u'%s <sourcefile>' % os.path.basename(__file__))

    else:
        gs = GrammarStore()

        fn = os.path.realpath(sys.argv[1])
        dirn = os.path.dirname(fn)
        ctagsn = os.path.join(dirn, u'ctags')
        call_tagsn = os.path.join(dirn, u'call_tags')
        ctags = open(ctagsn, u'wt')
        call_tags = open(call_tagsn, u'wt')

        fmt = CTagsFormatter(fn, ctags, call_tags)
        with open(fn, u'rb') as f:
            gs.parse_document(fn, f, fmt)

        ctags.close()
        call_tags.close()
