#!/usr/bin/python
# coding: utf-8

# Copyright (c) 2014 Mountainstorm
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


import os
import sys
from theme import ThemeStore
from grammar import GrammarStore
from console_formatter import ConsoleFormatter


if __name__ == u'__main__':
    if len(sys.argv) < 2:
        print(u'%s list|<sourcefile> [<theme class>]' % os.path.basename(__file__))

    else:
        ts = ThemeStore()
        if sys.argv[1] == u'list':
            print(u'Themes:')
            for t in ts.themes.keys():
                print(u'    %s' % t)
        else:
            gs = GrammarStore()

            theme = ts.themes.values()[0]
            if len(sys.argv) == 3:
                theme = ts.get_theme(sys.argv[2])

            fmt = ConsoleFormatter(sys.stdout, theme, tab=4)
            with open(sys.argv[1], u'rb') as f:
                gs.parse_document(sys.argv[1], f, fmt)
